config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]

  root to: 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github google_oauth2]

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :photos, dependent: :destroy

  has_one_attached :avatar, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_fill: [25, 25]
    attachable.variant :avatar, resize_to_fill: [350, 350]
  end

  before_save :downcase_email

  validates :name, presence: true, length: { maximum: 35 }

  after_commit :link_subscriptions, on: :create

  def author?(event)
    event.user == self
  end

  def self.github_from_omniauth(access_token)
    # Достаём email из токена
    email = access_token.info.email
    name = access_token.info.name
    user = where(email: email).first

    # Возвращаем, если нашёлся
    return user if user.present?

    # Если не нашёлся, достаём провайдера, айдишник и урл
    provider = access_token.provider
    url = "https://github.com/#{name}"

    # Теперь ищем в базе запись по провайдеру и урлу
    # Если есть, то вернётся, если нет, то будет создана новая
    where(url: url, provider: provider).first_or_create! do |user|
      # Если создаём новую запись, прописываем email и пароль
      user.name = name
      user.email = email
      user.password = Devise.friendly_token.first(16)
    end
  end

  def self.google_from_omniauth(access_token)
    email = access_token.info.email
    name = access_token.info.name
    user = where(email: email).first

    return user if user.present?

    provider = access_token.provider
    url = "https://plus.google.com/+#{name.gsub(/\s+/, '')}" # не смог найти возможность получения корректной ссылк на профиль

    where(url: url, provider: provider).first_or_create! do |user|
      user.name = name
      user.email = email
      user.password = Devise.friendly_token.first(16)
    end
  end

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: email).update_all(user_id: id)
  end

  def downcase_email
    email.downcase! if email.present?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # Дёргаем метод модели, который найдёт пользователя
    @user = User.github_from_omniauth(request.env['omniauth.auth'])

    # Если юзер есть, то логиним и редиректим на его страницу
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'Github')
      sign_in_and_redirect @user, event: :authentication

      # Если неудачно, то выдаём ошибку и редиректим на главную
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      flash[:error] = I18n.t(
        'devise.omniauth_callbacks.failure',
        kind: 'Facebook',
        reason: 'authentication error'
      )

      redirect_to root_path
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.google_from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'Google')
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      flash[:error] = I18n.t(
        'devise.omniauth_callbacks.failure',
        kind: 'Google',
        reason: 'authentication error'
      )

      redirect_to root_path
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create]

  def create
    super
    UserMailer.with(user: @user).sign_in.deliver_now if @user.persisted?
  end

  private

  def check_captcha
    return if verify_recaptcha # verify_recaptcha(action: 'signup') for v3

    self.resource = resource_class.new sign_up_params
    resource.validate # Look for any other validation errors besides reCAPTCHA
    set_minimum_password_length

    respond_with_navigational(resource) do
      flash.discard(:recaptcha_error) # We need to discard flash to avoid showing it on the next page reload
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, except: %i[show]
  before_action :authenticate_user!, except: %i[show]

  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: t('controllers.users.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/views/users/_form.html.erb
<div class="row pt-3">
  <div class="col-md-6">
    <%= form_with model: @user do |f| %>
      <%= render partial: 'partials/form_errors', locals: { errors: @user.errors } %>

      <div class="pt-3">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="pt-3">
        <%= f.label :email, class: 'form-label' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <%= f.label :avatar, class: 'form-label' %>
      <%= f.file_field :avatar, class: 'form-control' %>
      </div>

      <div class="pt-3">
        <%= f.label :avatar, class: 'form-label' %>
        <p><%= image_tag(user_avatar_thumb(@user)) if @user.avatar.attached? %></p>
        <%= f.file_field :avatar %>
      </div>

      <div class="pt-3">
        <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
        или <%= link_to 'вернуться', :back %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<span class="rounded-circle">
    <%= image_tag(user_avatar_thumb(user), class: 'rounded-circle') %>
</span>
<% if request.path == user_path(user) %>
  <%= user.name %>
<% else %>
  <%= link_to user.name, user_path(user) %>
<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<div class="row">
  <div class="col-md-6 pt-3">
    <%= render 'form' %>
  </div>

  <p class="pt-2">
    <%= link_to 'Редактировать пароль', edit_user_registration_path %>
  </p>

</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>
  <%= image_tag user_avatar(@user), class: 'rounded-circle' %>
  <% if @user == current_user %>
    <p class="py-2">
      <%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-secondary' %>
    </p>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
        <h3>Организовал: <%= @user.events.count %> <%= translate(:events, :count => @user.events.count) %></h3>
        <div class="row">
          <%= render partial: 'events/event', collection: @user.events %>
        </div>
      <% else %>
        <p class="pt-2">Пользователь не организовал ни одного события</p>
      <% end %>
    </div>

  </div>
</div>