config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]

  root to: 'events#index'
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize_to_fill: [100, 100]
    attachable.variant :show, resize_to_fill: [350, 350]
  end

  validates :photo, file_content_type: { allow: %w[image/png image/jpg image/jpeg image/webp] }

  belongs_to :event
  belongs_to :user

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: %i[create destroy]
  before_action :set_photo, only: %i[destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.photo.attached? && @new_photo.save
      SendNotification.perform_later(event: @event, notification: @new_photo)

      redirect_to @event, notice: t("controllers.photos.created")
    else
      render 'events/show', alert: t('controllers.photos.error'), status: :unprocessable_entity
    end
  end

  def destroy
    message = { notice: t("controllers.photos.destroyed"), status: :see_other }

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = { alert: t("controllers.subscriptions.error"), status: :see_other }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:event, :photo)
  end
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo] do |f| %>
  <%= render partial: 'partials/form_errors', locals: { errors: photo.errors } %>

  <div class="row">
    <p class="my-0 py-1"><%= t('views.photos.form.title') %></p>
    <div class="col">
      <div class="pt-3">
        <%= f.file_field :photo, class: 'form-control' %>
      </div>
    </div>
    <div class="col-auto">
      <div class="col-md-12 pt-3">
        <div class="actions">
          <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<% image_title = render partial: 'photos/photo_title', locals: { photo: photo } %>
<%= link_to image_tag(photo_thumb(photo)), photo_show(photo), data: {lightbox: "roadtrip", title: image_title} if photo_show(photo) %>

app/views/photos/_photo_title.html.erb
<%= render partial: 'users/user', object: photo.user %>
<% if current_user_can_edit?(photo) %>
  <%= link_to(event_photo_path(photo.event, photo), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }) do %>
    <i class="bi-trash" role="img" aria-label="to_trash"></i>
  <% end %>
<% end %>